version: '2'
services:
  mysql_db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql_db
  admin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - '8080:80'
    links:
      - mysql_db:db
    depends_on:
      - mysql_db
volumes:
  db:
